steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/price-crawler', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/price-crawler']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
