substitutions:
  _SERVICE: "price-crawler"
  _REGION: "me-west1"
  _GCS_BUCKET: "civic-ripsaw-466109-e2-crawler-data"

images:
  - "gcr.io/$PROJECT_ID/zilazol:$COMMIT_SHA"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zilazol:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zilazol:latest'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/zilazol']
  
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy to Cloud Run"
    entrypoint: bash
    args:
      - -ceu
      - |
        echo "Deploying image gcr.io/$PROJECT_ID/zilazol:$COMMIT_SHA"
        gcloud run deploy ${_SERVICE} \
          --image gcr.io/$PROJECT_ID/zilazol:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --memory 16Gi \
          --cpu 4 \
          --timeout 3600 \
          --set-env-vars RELEASE=$COMMIT_SHA,GCS_BUCKET=${_GCS_BUCKET} \
          --set-secrets="DATABASE_URL=DATABASE_URL:latest" \
          --allow-unauthenticated \
          --project $PROJECT_ID
        echo "Traffic:"
        gcloud run services describe ${_SERVICE} \
          --region ${_REGION} \
          --project $PROJECT_ID \
          --format='value(status.latestReadyRevisionName,status.traffic)'
        echo "Image digest:"
        gcloud run revisions describe $(gcloud run services describe ${_SERVICE} --region ${_REGION} --project $PROJECT_ID --format='value(status.latestReadyRevisionName)') \
          --region ${_REGION} \
          --project $PROJECT_ID \
          --format='value(status.imageDigest)'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
